import { Card } from "../../Components"

const Orders: React.FC = () => {
    return (<div className="grid grid-cols-2 gap-4">
        <Card>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
        </Card>
        <Card>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
        </Card>
        <Card>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
        </Card>
        <Card>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
        </Card>
        <Card>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
        </Card>
        <Card>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
        </Card>
        <Card>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
        </Card>
        <Card>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
        </Card>
        <Card>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
        </Card>
        <Card>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
        </Card>
        <Card>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
            <p>dhshjdskj</p>
        </Card>
    </div>)
}

export default Orders